config/routes.rb
Rails.application.routes.draw do

  resources :completed_appointments

  devise_for :users

  get 'users/sign_in'
  delete 'users/sign_out'
  get 'users/sigh_up'

  root 'welcome#index'

  resources :appointments

  resources :diagnostics

  resources :physicians

  resources :patients

  resources :users

  resources :invoices

  get 'invoices/index'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :appointment
  has_many :diagnostics, through: :appointment
  has_many :patients, through: :appointment
  has_many :physicians, through: :appointment
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @invoices = Invoice.all
    respond_with(@invoices)
  end

  def show
    respond_with(@invoice)
  end

  def new
    @invoice = Invoice.new
    respond_with(@invoice)
  end

  def edit
  end

  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.save
    respond_with(@invoice)
  end

  def update
    @invoice.update(invoice_params)
    respond_with(@invoice)
  end

  def destroy
    @invoice.destroy
    respond_with(@invoice)
  end

  private
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    def invoice_params
      params.require(:invoice).permit(:appointment_id)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :appointment_id %><br>
    <%= f.collection_select :appointment_id, Appointment.all,:id,:appointment_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<h1>Listing invoices</h1>

<table>
  <thead>
    <tr>
      <th>Appointment ID</th>
      <th>Appointment Date/Time</th>
      <th>Patient Last Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.appointment_id %></td>
        <td><%= invoice.appointment.appointment_date %></td>
        <td><%= invoice.appointment.patient.patient_last_name %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Appointment ID:</strong>
  <%= @invoice.appointment_id %>
</p>

<p>
  <strong>Appointment Date/Time:</strong>
  <%= @invoice.appointment.appointment_date %>
</p>

<p>
  <strong>Patient Last Name:</strong>
<%= @invoice.appointment.patient.patient_last_name %>
</p>

<p>
  <strong>Physician Last Name:</strong>
  <%= @invoice.appointment.physician.physician_last_name %>
</p>

<p>
  <strong>Diagnostic Code:</strong>
  <%= @invoice.appointment.diagnostic.diagnostic_code %>
</p>

<p>
  <strong>Diagnostic Charge:</strong>
  <%= @invoice.appointment.diagnostic.diagnostic_charge %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>