config/routes.rb
Rails.application.routes.draw do

  resources :completed_appointments

  devise_for :users

  get 'users/sign_in'
  delete 'users/sign_out'
  get 'users/sigh_up'

  root 'welcome#index'

  resources :appointments

  resources :diagnostics

  resources :physicians

  resources :patients

  resources :users

  resources :invoices

  get 'invoices/index'

end

app/models/completed_appointment.rb
class CompletedAppointment < ActiveRecord::Base

  belongs_to :appointment
  has_many :diagnostics, through: :appointments
  has_many :patients, through: :appointments
  has_many :physicians, through: :appointments


end

app/controllers/completed_appointments_controller.rb
class CompletedAppointmentsController < ApplicationController
  before_action :set_completed_appointment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @completed_appointments = CompletedAppointment.all
    respond_with(@completed_appointments)
  end

  def show
    respond_with(@completed_appointment)
  end

  def new
    @completed_appointment = CompletedAppointment.new
    respond_with(@completed_appointment)
  end

  def edit
  end

  def create
    @completed_appointment = CompletedAppointment.new(completed_appointment_params)
    @completed_appointment.save
    respond_with(@completed_appointment)
  end

  def update
    @completed_appointment.update(completed_appointment_params)
    respond_with(@completed_appointment)
  end

  def destroy
    @completed_appointment.destroy
    respond_with(@completed_appointment)
  end

  private
    def set_completed_appointment
      @completed_appointment = CompletedAppointment.find(params[:id])
    end

    def completed_appointment_params
      params.require(:completed_appointment).permit(:appointment_id)
    end
end

app/helpers/completed_appointments_helper.rb
module CompletedAppointmentsHelper
end

app/views/completed_appointments/_form.html.erb
<%= form_for(@completed_appointment) do |f| %>
  <% if @completed_appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@completed_appointment.errors.count, "error") %> prohibited this completed_appointment from being saved:</h2>

      <ul>
      <% @completed_appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :appointment_id %><br>
    <%= f.collection_select :appointment_id, Appointment.all,:id,:appointment_id, {}, {:multiple => true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/completed_appointments/edit.html.erb
<h1>Editing completed_appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @completed_appointment %> |
<%= link_to 'Back', completed_appointments_path %>

app/views/completed_appointments/index.html.erb
<h1>Previously Generated Reports</h1>

<table>
  <thead>
    <tr>
      <th>Appointment ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @completed_appointments.each do |completed_appointment| %>
      <tr>
        <td><%= completed_appointment.appointment_id %></td>
        <td><%= link_to 'Show', completed_appointment %></td>
        <td><%= link_to 'Edit', edit_completed_appointment_path(completed_appointment) %></td>
        <td><%= link_to 'Destroy', completed_appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_completed_appointment_path %>

app/views/completed_appointments/new.html.erb
<h1>New completed_appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', completed_appointments_path %>

app/views/completed_appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Physician Last Name:</strong>
  <%= @completed_appointment.appointment.physician.physician_last_name %>
</p>

<p>
  <strong>Appointment ID:</strong>
  <%= @completed_appointment.appointment_id %>
</p>

<p>
  <strong>Appointment Date/Time:</strong>
  <%= @completed_appointment.appointment.appointment_date %>
</p>

<p>
  <strong>Diagnostic Charge:</strong>
  <%= @completed_appointment.appointment.diagnostic.diagnostic_charge %>
</p>

<%= link_to 'Edit', edit_completed_appointment_path(@completed_appointment) %> |
<%= link_to 'Back', completed_appointments_path %>